app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


class Quote:
    '''
    Quotes class to define quotes object
    '''

    def __init__(self, author, quote):
        self.author = author
        self.quote = quote


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    firstname = db.Column(db.String(255))
    lastname = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    subscription = db.Column(db.Boolean)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String)
    password_hash = db.Column(db.String(255))
    date_joined = db.Column(db.DateTime, default=datetime.utcnow)

    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    posts = db.relationship('Post', backref='user', lazy="dynamic")

    comments = db.relationship('Comment', backref='user', lazy="dynamic")

    @property
    def password(self):
        raise AttributeError('You cannnot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'User {self.username}'


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    users = db.relationship('User', backref='role', lazy="dynamic")

    def __repr__(self):

        return f'User {self.name}'


class Post(db.Model):
    __tablename__ = 'posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())
    text = db.Column(db.String())
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    date_posted = db.Column(db.DateTime, default=datetime.utcnow)

    comments = db.relationship('Comment', backref='post_id', lazy='dynamic')

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    def get_post(id):
        post = Post.query.filter_by(id=id).first()

        return post


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(1000))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post = db.Column(db.Integer, db.ForeignKey('posts.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, post):
        comments = Comment.query.filter_by(post=post.id).all()

        return comments


class PhotoProfile(db.Model):
    __tablename__ = 'profile_photos'

    id = db.Column(db.Integer, primary_key=True)
    pic_path = db.Column(db.String())
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Required


class PostForm(FlaskForm):

    title = StringField('Title', validators=[Required()])
    text = TextAreaField('Text', validators=[Required()])
    submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Bio.', validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    text = TextAreaField('Leave a comment:', validators=[Required()])
submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = "strong"
login_manager.login_view = "auth.login"

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos', IMAGES)
mail = Mail()


def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    #  configure UploadSet
    configure_uploads(app, photos)

    # Registering the blueprint
    from .main import main as main_blueprint

    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint

    app.register_blueprint(auth_blueprint, url_prefix="/authenticate")

    # setting config
    # from .request import configure_request

    # configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, error,forms

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from ..models import User, Post, Comment
from .. import db
from .forms import PostForm, CommentForm
from flask_login import login_required, current_user
import datetime
from ..email import mail_message
from ..request import get_quotes

# views
@main.route("/")
def index():
    '''
    View root page function that returns the index page and its data
    '''
    random_quote = get_quotes()

    posts = Post.query.order_by(Post.date_posted.desc()).limit(3).all()

    title = "Home - Welcome to the best Blog page"

    return render_template("index.html", title=title, posts=posts, quote = random_quote)


@main.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    post_form = PostForm()
    if post_form.validate_on_submit():
            title = post_form.title.data
            text = post_form.text.data

            users = User.query.all()

            # Update pitch instance
            new_post = Post(title=title, text=text)

            # Save post method
            new_post.save_post()

            for user in users:
                if user.subscription:
                    mail_message("New Post", "email/new_post",
                                 user.email, user=user)

            return redirect(url_for('.index'))

    # else:
    #     return redirect(url_for('.index'))

    title = 'New post'
    return render_template('new_post.html', title=title, post_form=post_form)


@main.route('/posts')
def all_posts():
    posts = Post.query.order_by(Post.date_posted.desc()).all()

    title = 'Blog posts'

    return render_template('posts.html', title=title, posts=posts)


@main.route('/post/<int:id>', methods=['GET', 'POST'])
def post(id):
    form = CommentForm()
    post = Post.get_post(id)

    if form.validate_on_submit():
        comment = form.text.data

        new_comment = Comment(comment=comment, user=current_user, post=post.id)

        new_comment.save_comment()

    comments = Comment.get_comments(post)

    title = f'{post.title}'
    return render_template('post.html', title=title, post=post, form=form, comments=comments)


@main.route('/delete_comment/<id>/<post_id>', methods=['GET', 'POST'])
def delete_comment(id, post_id):
    comment = Comment.query.filter_by(id=id).first()

    db.session.delete(comment)
    db.session.commit()

    return redirect(url_for('main.post', id=post_id))


@main.route('/delete_post/<id>', methods=['GET', 'POST'])
def delete_post(id):
    post = Post.query.filter_by(id=id).first()

    db.session.delete(post)
    db.session.commit()

    return redirect(url_for('main.all_posts'))


@main.route('/subscribe/<id>')
def subscribe(id):
    user = User.query.filter_by(id=id).first()

    user.subscription = True

    db.session.commit()

    return redirect(url_for('main.index'))


@main.route('/post/update/<id>', methods=['GET', 'POST'])
def update_post(id):
    form = PostForm()

    post = Post.query.filter_by(id=id).first()

    form.title.data = post.title
    form.text.data = post.text

    if form.validate_on_submit():
        title = form.title.data
        text = form.text.data

        post.title = title
        post.text = text

        db.session.commit()

        return redirect(url_for('main.post', id=post.id))

    return render_template('update.html', form=form)


@main.route('/user/<uname>')
def profile(uname):
    '''
    Profile page of user
    '''
    user = User.query.filter_by(username=uname).first()
    user_joined = user.date_joined.strftime('%b %d, %Y')

    if user is None:
        abort(404)

    return render_template('profile/profile.html', user=user, date=user_joined)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}

{{ super() }}

<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

<!-- Nucleo Icons -->
<link href="{{ url_for('static' ,filename='css/nucleo-icons.css') }}" rel="stylesheet" />

<!-- CSS Files -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/blk-design-system.css')}}">

<script src="{{ url_for('static', filename='js/plugins/perfect-scrollbar.jquery.min.js') }}"></script>

<script src="{{ url_for('static', filename='js/plugins/bootstrap-switch.js') }}"></script>

<script src="{{ url_for('static', filename='js/plugins/nouislider.min.js') }}"></script>

<script src="{{ url_for('static', filename='js/plugins/chartjs.min.js') }}"></script>

<script src="{{ url_for('static', filename='js/plugins/moment.min.js')}}"></script>
<script src=" {{ url_for('static', filename='js/plugins/bootstrap-datetimepicker.js') }}"></script>

<script src="{{ url_for('static', filename='js/blk-design-system.js') }}"></script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% endblock %}


<!--Navbar Block-->



{% include 'navbar.html' %}

app/templates/fourOWfour.html
{% extends 'base.html' %}

{% block content %}

    <h1> WHOOPS we can't find that page </h1>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}

<!-- Content block -->
{% block content%}

<div class="wrapper">
    <div class="page-header header-filter">
        <div class="squares square1"></div>
        <div class="squares square2"></div>
        <div class="squares square3"></div>
        <div class="squares square4"></div>
        <div class="squares square5"></div>
        <div class="squares square6"></div>
        <div class="squares square7"></div>
        <div class="container">
          {%for quote in quote%}
            <p>{{quote.quote}}</p>
            <i>{{quote.author}}</i>
          {%endfor%}
        </div>
    </div>

    {% if posts == 'None' %}
    <div class="section section-nucleo-icons">

        <div class="container">

            <div class="row justify-content-center">

                <div class="col-lg-8 col-md-12">

                    <h2 class="title"> BLOGS </h2>

                    <h4 class="description">
                        There are no posted blogs yet.
                    </h4>

                </div>

            </div>

        </div>



    </div>

    {% else %}
    <div class="section section-typo">

        <div class="container">
            <div id="typography">
                <div class="row">
                    <div class="col-md-12">

                        <div class="typography-line">

                            {{ macro.displayPosts(posts) }}

                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>

    {% endif %}
</div>

{% endblock %}

app/templates/macros.html
{% macro displayPosts(post_list)%}
{%for post in post_list%}

<blockquote>
    <h3 class="text-center" > {{ post.title | capitalize }} </h3>
    <p class="blockquote blockquote-primary">
        {{ post.text }}
        <br>
        <br>
        <small>
            Posted on : {{post.date_posted.strftime('%Y-%m-%d')}}
            <a href="/post/{{post.id}}"
                class="btn btn-primary pull-right">Read&raquo;</a>
        </small>
    </p>
</blockquote>



<!-- <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
    <div class="well well-lg" style="background-color: white;">
        <h4>{{post.title}}</h4>
        <p>{{post.text| truncate(120)}}</p>
        <p>Posted on: {{post.date_posted.strftime('%Y-%m-%d')}} <a href="/post/{{post.id}}"
                class="btn btn-primary pull-right">Read</a></p>
    </div>
</div> -->
{%endfor%}
{%endmacro%}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg fixed-top navbar-transparent " color-on-scroll="100">
    <div class="container">
        <div class="navbar-translate">
            <a class="navbar-brand" href="/" rel="tooltip" title="BLog website" data-placement="bottom">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor"
                    stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img"
                    viewBox="0 0 24 24" focusable="false">
                    <title>Pitch App</title>
                    <circle cx="12" cy="12" r="10" />
                    <path
                        d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" />
                </svg>
            </a>
            <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <div class="navbar-collapse-header">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a>
                            BLOG WEBSITE•
                        </a>
                    </div>
                    <div class="col-6 collapse-close text-right">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navigation"
                            aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="tim-icons icon-simple-remove"></i>
                        </button>
                    </div>
                </div>
            </div>
            <ul class="navbar-nav mr-auto">
                <li class="py-2 d-none d-md-inline-block">
                    <a class="nav-link" rel="tooltip" title="Follow us on Twitter" data-placement="bottom"
                        href="https://twitter.com/" target="_blank">
                        <i class="fab fa-twitter"></i>
                        <p class="d-lg-none d-xl-none">Twitter</p>
                    </a>
                </li>
                <li class="py-2 d-none d-md-inline-block">
                    <a class="nav-link" rel="tooltip" title="Like us on Facebook" data-placement="bottom"
                        href="https://www.facebook.com/" target="_blank">
                        <i class="fab fa-facebook-square"></i>
                        <p class="d-lg-none d-xl-none">Facebook</p>
                    </a>
                </li>
                <li class="py-2 d-none d-md-inline-block">
                    <a class="nav-link" rel="tooltip" title="Follow us on Instagram" data-placement="bottom"
                        href="https://www.instagram.com/" target="_blank">
                        <i class="fab fa-instagram"></i>
                        <p class="d-lg-none d-xl-none">Instagram</p>
                    </a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}

                <li class="dropdown nav-item">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                        <i class="fa fa-cogs d-lg-none d-xl-none"></i> {{current_user.username| capitalize}} <span
                            class="caret"></span>
                    </a>
                    <div class="dropdown-menu dropdown-with-icons">
                        <a href="{{ url_for('main.new_post') }}" class="dropdown-item">
                            <i class="tim-icons icon-bullet-list-67"></i>Post Blog
                        </a>
                        <a href="{{ url_for('main.profile',uname=current_user.username) }}" class="dropdown-item">
                            <i class="tim-icons icon-single-02"></i>Profile Page
                        </a>
                         <a href="{{ url_for('auth.logout') }}" class="dropdown-item">
                            <i class="tim-icons icon-image-02"></i>Sign Out
                        </a> 
                    </div>
                </li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}"><i class="tim-icons icon-single-02"></i>Sign in</a></li>
            </ul>
            {%endif%}

            </ul>



        </div>
    </div>
</nav>

app/templates/new_post.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    <div class="container">
        <div class="col-md-12">
            <h3>Create a post</h3>
            <hr>
            {{ wtf.quick_form(post_form) }}
        </div>

    </div>

{% endblock %}

app/templates/post.html
{% extends 'base.html'%}
{% import 'macros.html' as macro %}
{% import "bootstrap/wtf.html" as wtf %}


{%block content%}
<div class="wrapper">
    <div class="section section-nucleo-icons">

        <div class="container">

            <div class="row justify-content-center">

                <div class="col-lg-8 col-md-12">

                    <h2 class="title"> {{post.title | capitalize}} </h2>

                    <h4 class="description">
                        {{post.text}}
                    </h4>

                </div>



            </div>

        </div>
    </div>
    <div class="container" >

        <div class="row">
            <h4>Comments</h4>
            <hr>
            {% if current_user.is_authenticated %}
            {{ wtf.quick_form(form) }}
            {%endif%}
            {%for comment in comments%}
            <div class="col-md-12">
                <h5>{{comment.user.username | capitalize }}</h5>
                <p>{{comment.comment | capitalize }}</p>
                {% if current_user.is_authenticated and current_user.role_id == 1%}
                <a href="{{url_for('main.delete_comment',id = comment.id,post_id = comment.post)}}"
                class="btn btn-danger btn-sm">Delete comment</a>
                {%endif%}
            </div>
            {%endfor%}
        </div>
    </div>



    <!-- <div class="container">
        <div class="row">
            <h3>{{post.title}}</h3>
            <hr>
            <p>{{post.text}}</p>
            <span>
                <p>Posted on {{post.date_posted.strftime('%Y-%m-%d')}}</p>
                {% if current_user.is_authenticated and current_user.role_id == 1%}
                <a href="{{url_for('main.delete_post',id = post.id)}}" class="btn btn-danger btn-sm">Delete post</a>
                <a href="/post/update/{{post.id}}" class="btn btn-info btn-sm">Update post</a>
                {%endif%}
        </div>
        <div class="row">
            <h4>Comments</h4>
            <hr>
            {% if current_user.is_authenticated %}
            {{ wtf.quick_form(form) }}
            {%endif%}
            {%for comment in comments%}
            <div class="col-md-12">
                <h5>{{comment.user.username}}</h5>
                <p>{{comment.comment}}</p>
                {% if current_user.is_authenticated and current_user.role_id == 1%}
                <a href="{{url_for('main.delete_comment',id = comment.id,post_id = comment.post)}}"
                    class="btn btn-danger btn-sm">Delete comment</a>
                {%endif%}
            </div>
            {%endfor%}
        </div>
    </div> -->
</div>
<!-- <div class="modal-footer">
            <button type="button" class="btn btn-default">Nice Button</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div> -->
</div>


{%endblock%}

app/templates/posts.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}
<!-- Content block -->
{%block content%}
<div class="container">
    <h1>All posts</h1>
    <hr>
    {{macro.displayPosts(posts)}}
</div>
{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html' %}

{% block content%}

<body class="profile-page sidebar-collapse">

    <div class="wrapper">
        <div class="page-header">
            <div class="container align-items-center">
                <div class="row">
                    <div class="col-lg-6 col-md-6">

                        {% if user.firstname != 'None' %}
                        <h1 class="profile-title text-left">{{ user.username | capitalize }}</h1>

                        {% else %}

                        <h1 class="profile-title text-left">{{ user.firstname }} {{ user.lastname }} </h1>

                        {% endif %}
                        <h5 class="text-on-back">{{ user.username | capitalize}}</h5>

                        <!-- Displaying user bio -->
                        {% if user.bio == None %}
                        <p class="profile-description"> Please update your profile description </p>

                        {% else %}

                        <p class="profile-description"> {{ user.bio }} </p>

                        {% endif %}

                        <div class="btn-wrapper profile pt-3">
                            <a target="_blank" href="https://twitter.com/" class="btn btn-icon btn-twitter btn-round"
                                data-toggle="tooltip" data-original-title="Follow us">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a target="_blank" href="https://www.facebook.com/"
                                class="btn btn-icon btn-facebook btn-round" data-toggle="tooltip"
                                data-original-title="Like us">
                                <i class="fab fa-facebook-square"></i>
                            </a>
                            <a target="_blank" href="https://dribbble.com/" class="btn btn-icon btn-dribbble  btn-round"
                                data-toggle="tooltip" data-original-title="Follow us">
                                <i class="fab fa-dribbble"></i>
                            </a>
                        </div>
                    </div>

                    <div class="col-lg-4 col-md-6 ml-auto mr-auto">
                        <div class="card card-coin card-plain">
                            <div class="card-header">
                                {% if user.profile_pic_path %}
                                <img src="{{url_for('static',filename=user.profile_pic_path)}}"
                                    class="img-center img-fluid rounded-circle shadow" style="width: 150px;">
                                {% else %}

                                <img src="/static/img/rust.jpg" class="img-center img-fluid rounded-circle shadow"
                                    style="width: 150px;">

                                {% endif %}



                                <h1 class="title"> {{ user.username | capitalize  }} </h1>
                            </div>
                            <div class="card-body">

                                <p class="profile-description text-left"> Please give a description of what you of your
                                    achievemnts and projects that you are working on</p>
                                <div class="btn-wrapper pt-3">
                                    <button href="javascript:void(0)" class="btn btn-simple btn-primary">
                                        <i class="tim-icons icon-book-bookmark"></i> Follow
                                        {{ user.username | capitalize }}
                                    </button>
                                    <button href="javascript:void(0)" class="btn btn-simple btn-info">
                                        <i class="tim-icons icon-bulb-63"></i> Message
                                    </button>





                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</body>

{% endblock %}

app/templates/styles.html
{% block styles %}
<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

<!-- Nucleo Icons -->
<link href="{{ url_for('static' ,filename='css/nucleo-icons.css') }}" rel="stylesheet" />

<!-- CSS Files -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/blk-design-system.css')}}">

<script src="{{ url_for('static', filename='js/plugins/perfect-scrollbar.jquery.min.js') }}"></script>

<script src="{{ url_for('static', filename='js/plugins/bootstrap-switch.js') }}"></script>

<script src="{{ url_for('static', filename='js/plugins/nouislider.min.js') }}"></script>

<script src="{{ url_for('static', filename='js/plugins/chartjs.min.js') }}"></script>

<script src="{{ url_for('static', filename='js/plugins/moment.min.js')}}"></script>
<script src=" {{ url_for('static', filename='js/plugins/bootstrap-datetimepicker.js') }}"></script>

<script src="{{ url_for('static', filename='js/blk-design-system.js') }}"></script>

{% endblock %}

app/templates/update.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
    <div class="col-md-12">
        <h3>Update post</h3>
        <hr>
        {{ wtf.quick_form(form) }}

    </div>

</div>

{% endblock %}